spring:
  application:
    name: ggukgguki-api
  datasource:
    url: jdbc:mysql://localhost:3307/ggukgguki?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useUnicode=true
    username: ggukgguki
    password: ggukgguki
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:dGhpcyBpcyBhIGRldmVsb3BtZW50LW9ubHkgc2VjcmV0IGtleQ==}
  access-expiration: 1800000
  refresh-expiration: 604800000

google:
  client-id: ${GOOGLE_CLIENT_ID:356220366807-71q5so2s2d9a1pmf1j2vs0h82tvsf7in.apps.googleusercontent.com}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method
  api-docs:
    path: /v3/api-docs
